### PR TITLE
fix: update v-content to v-main for vuetify 2.3.0

### PR DESCRIPTION
**Pull request by benyou1969**
Change `v-content` to `v-main`

Vuetify version: [v2.3.0](https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.0)

### CODE REVIEW

**Comment by schlunsen** [comment]
Is this ready for merge?

**Comment by steklopod** [comment]
The project seems to be dead :-(

**Comment by schlunsen** [comment]
@kevinmarrec Any updates on when we can merge this?

**Comment by ianfortier** [comment]
You can update the Vuetify version using 
`npm update vuetify --depth 2`

**Comment by schlunsen** [comment]
@pi0 This project seems dead. How can we relive this again and maybe look for new maintainers? Makes sense that it's maintained in this repo

**Comment by nicomoya123** [comment]
I would like to try and maintain the project,
How can I do it

**Comment by daniluk4000** [comment]
My gosh finally. Thanks

**Pull request merged**
