### PR TITLE
Fix error when import lang module

### PR DESCRIPTION
**Pull request by MrJmpl3**
The transpile of webpack need be `'vuetify'` or the regex `/^vuetify/`

Issue: https://github.com/nuxt-community/vuetify-module/issues/198

Are you need look where i took the fixes?, look the repo of vuetify for vue-cli: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/master/packages/vue-cli-plugin-vuetify/generator/tools/vuetify.js#L75

### CODE REVIEW

**Comment by MrJmpl3** [comment]
The CI fail because expected vuetify/lib in transpile .. 

https://github.com/nuxt-community/vuetify-module/blob/master/test/module.test.ts#L133

**Comment by kevinmarrec** [comment]
@MrJmpl3  AFAIK It used to be a regex : https://github.com/nuxt-community/vuetify-module/blob/0.x/lib/module.js#L34 , but I remember of an issue somehow that made me change it.
It might have been related to performance (bundle size) or build time.

Do you any big project that works fine with this change ?

**Comment by MrJmpl3** [comment]
I used regex since V1 .. For my system of electronic billing of my country, with more 30 company.
Maybe was a bug from the Vuetify 2 core. Remember when release the V2 has some bug of perfomance.

**Comment by MrJmpl3** [comment]
@kevinmarrec The bug of performance was with only Nuxt? Because in Vue-cli don't use regex.

Use a simple string.. https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/master/packages/vue-cli-plugin-vuetify/generator/tools/vuetify.js#L75

**Comment by kevinmarrec** [comment]
Yeah, seems it just should be `vuetify`, I'll do some tests later this day, and if just feel relevant I'll merge & do 2 releases (needs to be fixed around `next` branch for v2 alpha version of the module as well).

**Comment by MrJmpl3** [comment]
@kevinmarrec I look the code and don't implement the fibers plugin in sass loader ..

https://www.npmjs.com/package/fibers

https://github.com/nuxt-community/vuetify-module/blob/master/src/sass.ts

**Comment by kevinmarrec** [comment]
@MrJmpl3 As I think it could break some projects that use `es5` imports instead of `lib` (or at least in my case I have been able to see a warning) , I prefer targeting this change only around `next` branch.

**Comment by kevinmarrec** [comment]
Closing in favor of https://github.com/nuxt-community/vuetify-module/commit/059ca8cffc90cdb6019a1d88a94264c5b7ff466e

Thanks for your time :green_heart:

**Pull request closed without merging**
