### PR TITLE
v2.0@alpha - Module revamp

### PR DESCRIPTION
**Pull request by kevinmarrec**
# Progression

- [x] Refactor how SASS/SCSS variables are prepended with `sass-loader`
- [x] Turns [**fibers**](https://www.npmjs.com/package/fibers) to an optional dependency
- [x] Rename **optionsPath** to **frameworkOptions**
- [x] Automatic imports (**option to enable/disable it**) #154 
- [x] Bump Vuetify version to **2.1** when it comes up
- [x] Upgrade example (https://github.com/nuxt-community/vuetify-module/tree/master/test/fixture) to last Vuetify VGrid specifications
- [x] ~~Progressive images #167 ~ optional dependency **ImageMagick** will be required~~ (**POSTPONED to next release**)

# Breaking changes

> Several breaking changes are planned through this revamp, there will be listed here and in release notes.

## 1) Vuetify framework options
Vuetify framework options (**theme**, **breakpoints**, etc.) must now be given to **frameworkOptions** module option, which means you can't give framework options through the root module options as before (i.e. **vuetify.theme** -> **vuetify.frameworkOptions.theme**)

**frameworkOptions** replaces **optionsPath** and it can then also be a path to the file that contains the framework options.

## 2) Tree shaking

**treeShake** option has been removed from the module options.

The Vuetify module will always now import **Vuetify** from `vuetify/lib` which will provide natural tree shaking with Webpack.

You may notice longer build in development mode if you never change **treeShake** value, cause it was previously using full bundle **dist/vuetify.js** + **dist/vuetify/css** in development environement by default to have faster build.
There is no longer way to use this full bundle anymore as it's considered as bad practices and was leading to **CSS order issue**, as well as not being able to **customize SASS variables**.

**treeShake** option was overall using **vuetify-loader** to automatically import Vuetify components in your own components in a transparent way. 

This behavior has been moved to a new option **automaticImports**, which is now enabled by default and can be disabled if you want to have full control of Vuetify component imports, such as being able to lazy load them (**vuetify-loader** doesn't provide lazy loading of the Vuetify components).

## 3) Global imports

Global imports where used to be **treeShake** options : **treeShake.components**, **treeShake.directives** & **treeShake.transitions**.

They have now been isolated under **globalImports** module option (**globalImports.components**, **globalImports.directives** & **globalImports.transitions**)

## 4) [**Fibers**](https://www.npmjs.com/package/fibers) optional dependency

[**Fibers**](https://www.npmjs.com/package/fibers) is now optional cause of different use cases where some users couldn't install the module cause of operating system requirements (**i.e.** it mostly needs `python` to build sources)

It means that if you still want to use it (was shipped with the module before), you just need to install it as devDependency in your project :

```sh
yarn add --dev fibers
# OR
npm install --save-dev fibers
```

**fibers** is here to make `sass-loader` faster, and is automatically detected and used if installed since `sass-loader@8`.

# Migration guide ~ Alpha / Beta / Release Candidate

A proper migration guide will be delivered when first release candidate (**2.0.0-rc.0**) will be published. If you want to try alpha/beta stages. Please read the PR descriptions and/or commit changes for now.

### CODE REVIEW

**Comment by chanlito** [comment]
Can't wait for next release. 👍

**Comment by chanlito** [comment]
I agree, not everyone uses progressive images. 
I know It's nice to have, but let's solve one thing at a time. I believe most people having trouble with overriding Vuetify styles.

**Comment by praburangki** [comment]
Thanks for the work man. Can't wait to get the new updates. Development time is kind of slow when overriding the sass variables. After my company has a stable product, I would love to contribute to this module.

**Comment by steklopod** [comment]
Thanks a lot. I have a question about breaking changes: Does my `nuxt.config.js` right?
```js
    vuetify: {
        defaultAssets: false,
        icons: {iconfont: 'mdiSvg', values: overriddenMdiIcons},
        lang: {locales: {ru, en}, current: 'ru'},
        customVariables: ['~/assets/style/variables.scss'],
        frameworkOptions: {
            theme: {
                options: {customProperties: true},
                themes: {
                    light: {
                        secondary: colors.indigo.accent1,
                        accent: colors.deepOrange.accent2,
                        darken: colors.grey.darken3,
                    },
                    dark: {
                        darken: colors.grey.lighten3,
                    }
                }
            }
        }
    }
```

**Comment by garan82** [comment]
Do you have a timeline for beta/RC release?

**Comment by gotenxds** [comment]
@kevinmarrec It looks like now we have to provide all of the frameworkOptions if we want to provide any, previously you could just provide what you wanted but the new types are all mandatory

for example previously we did:
```
  theme: {
      options: {
        customProperties: true,
      },
      themes: {
        light: {
          primary: {
            base: '#b71c1c',
            lighten1: '#f05545',
            darken1: '#7f0000',
          },
          secondary: {
            base: '#263238',
            lighten1: '#4f5b62',
            darken1: '#000a12'
          },
          error: '#FF5252',
          info: '#2196F3',
          success: '#4CAF50',
          warning: '#FFC107'
        }
      }
    }
```
the dark,
default
disable
and themses.dark options as well even though we dont need them, is this intentional ?
But now we need to provide

**Comment by kevinmarrec** [comment]
@gotenxds It's cause of Vuetify that change their types. It is not module issue.
The work around to still have autocompletion while not having the error is :
https://github.com/nuxt-community/vuetify-module/blob/master/test/fixture/vuetify.options.ts#L13

**Comment by gotenxds** [comment]
Thanks, I was beginning to lose my mind trying to fill it all with default stuff

**Comment by cuongicts** [comment]
Thanks for working hard. I'm still having custom variables problem with my company project.
It's takes 9 minutes to build :(

**Comment by garyo** [comment]
I just tried switching my project to 2.0.0-beta.0 (I need to customize background colors and the old version couldn't see the `variables.scss` in dev mode), but now my `yarn dev` crashes after 120 sec with a Javascript heap out of memory error. I do have fibers installed (4.0.2).
`yarn build` runs OK with this new module though. Just doesn't work in `dev` mode.

**Comment by chanlito** [comment]
@garyo agreed, played with it last night as well seems to be using too much memory.

**Pull request merged**
