### PR TITLE
fix(deps): fibers is optional dependency

### PR DESCRIPTION
**Pull request by sullivanpt**
Fibers is not required for a successful SASS build, many platforms don't have pre-built fibers binaries, and even in those cases where it could be built from source it usually doesn't make sense as the fibers compile time exceeds the SASS without fibers compile time.

This non-breaking commit makes fibers an optional dependency.

### CODE REVIEW

**Comment by kevinmarrec** [comment]
>  the fibers compile time exceeds the SASS without fibers compile time
@sullivanpt Do you have any evidences ?

**Comment by sullivanpt** [comment]
@kevinmarrec ok, you called my bluff. truth is I didn't get fibers to compile at all on CentOS 6, so I haven't measured it. Truth is, on my small SASS files I don't notice any difference with or without fibers.

But if you search the fibers issue list you'll find there are many other platforms where trying to compile fibers is a blocker.   This PR simply makes my life easier without any harmful impact.

**Comment by kevinmarrec** [comment]
@sullivanpt I know that fibers on heavy SASS files like Vuetify ones makes a performance boost (lower build time). So I still think fibers improves things around Vuetify module.

Still, you're right about `fibers` being known as a blocker, I got someone on Nuxt discord that had issue around Windows OS, and he wasn't able to install Python (probably cause he didn't have permissions to install it). And seems python is needed to build `fibers` sources.

I'm considering going your way and merge this PR for 2.0 release.

**Comment by sullivanpt** [comment]
@kevinmarrec very much appreciated.  For the record, in our situation, fibers precompiled installs and works as expected on our cutting edge developer machines (Win 10 and OS X) with node v.8; presumably providing a faster edit/test cycle.  But the maintenance developers on node v.8 had issues because the fibers@3/4 version mismatch. And as I already mentioned our CI build machines on CentOS 6 also have issues because the precompiled (fibers@4 for linux) binary isn't compatible.  Moving fibers to the optionalDependencies section means it "just works" for everybody.

Also, it should be a non-breaking change. No reason to wait for 2.0 that I can think of. We're already using it this way off the fork.

**Pull request merged**
