### PR TITLE
Update vuetify to v2.2.19

### PR DESCRIPTION
**Pull request by jeverduzco**

### CODE REVIEW

**Comment by abrooks693** [comment]
Any idea if this will be merged soon. Some bug fixes in here I require.

**Comment by aaharu** [comment]
@abrooks693 I think you can update the package without merging this commit.
`yarn upgrade` or `npm update vuetify --depth 2`

**Comment by abrooks693** [comment]
> @abrooks693 I think you can update the package without merging this commit.
> `yarn upgrade` or `npm update vuetify --depth 2`

Thank you so much, how did I not know this was a thing!

**Comment by jeverduzco** [comment]
> @abrooks693 I think you can update the package without merging this commit.
> `yarn upgrade` or `npm update vuetify --depth 2`

Thank you.

**Pull request closed without merging**
